# This GitHub Action bumps up the <Version /> tag in the csproj file depending on the commit's comment:
#   SemVer format is: MAJOR.MINOR.PATCH-PRERELEASE
#   If the commit's comment contains the string [MAJOR], [MINOR] or [PATCH] it bumps it accordingly.
#   If no matching bump commment is found, the PRERELEASE component gets bumped.
# Finally, it builds the project in .net 5 and .net 6, and publishes it to the local GitHub package registry.
# by @geoperez and @mariodivece
name: Pack and Publish
on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: 🧑‍💻 Checkout codebase
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MAD_PACKAGE_MGMNT }}
    - name: 🥓 Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          
  build-and-publish:
    uses: unosquare/swan/.github/workflows/ci-swan.yml@master
    with:
      project-name: 'Swan.Core'
    secrets:
      github-token: ${{ secrets.MAD_PACKAGE_MGMNT }}
