name: Publish Swan.Data.SqlBulkOps to Nuget.org
on: workflow_dispatch

jobs:
  publish-nuget:
    uses: unosquare/swan/.github/workflows/lib-publish-nuget-org.yml@master
    with:
      source-path: 'src/'
      project-name: 'Swan.Data.SqlBulkOps'
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
